# Generated by Django 3.2.20 on 2023-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Task Name')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Completed', 'completed')], max_length=200)),
            ],
        ),
    ]
